"""
Bugcheck code knowledge base.

Provides information about Windows bugcheck codes and common causes.
"""

from pathlib import Path
from typing import Optional, List


# Bugcheck code information database
BUGCHECK_CODES = {
    0x0A: {
        "name": "IRQL_NOT_LESS_OR_EQUAL",
        "description": "A driver tried to access a pageable memory address using an IRQL that was too high.",
        "common_causes": [
            "Faulty device driver",
            "Corrupted system files",
            "Incompatible software",
            "Memory corruption",
        ],
        "recommendations": [
            "Update all device drivers",
            "Run Windows System File Checker (sfc /scannow)",
            "Check for Windows updates",
            "Run a memory diagnostic",
        ],
    },
    0x3B: {
        "name": "SYSTEM_SERVICE_EXCEPTION",
        "description": "An exception happened while executing a routine that transitions from non-privileged code to privileged code.",
        "common_causes": [
            "Corrupted system files",
            "Video driver issues",
            "Antivirus software conflicts",
            "Disk corruption",
        ],
        "recommendations": [
            "Update video drivers",
            "Disable antivirus temporarily",
            "Run System File Checker",
            "Check disk for errors (chkdsk)",
        ],
    },
    0x13A: {
        "name": "KERNEL_MODE_HEAP_CORRUPTION",
        "description": "The kernel mode heap manager detected corruption in a heap.",
        "common_causes": [
            "Faulty driver corrupting memory",
            "Memory hardware issues",
            "Overclocking instability",
        ],
        "recommendations": [
            "Update all drivers",
            "Run memory diagnostic",
            "Disable overclocking",
            "Check for recently installed software",
        ],
    },
    0xD1: {
        "name": "DRIVER_IRQL_NOT_LESS_OR_EQUAL",
        "description": "A driver tried to access a memory address using an invalid IRQL.",
        "common_causes": [
            "Faulty or outdated driver",
            "Network driver issues",
            "Graphics driver problems",
        ],
        "recommendations": [
            "Update network and graphics drivers",
            "Disable recently installed hardware",
            "Update chipset drivers",
            "Check Event Viewer for driver errors",
        ],
    },
    0x50: {
        "name": "PAGE_FAULT_IN_NONPAGED_AREA",
        "description": "Invalid system memory was referenced.",
        "common_causes": [
            "Faulty RAM",
            "Corrupted drivers",
            "Disk corruption",
            "Antivirus conflicts",
        ],
        "recommendations": [
            "Run Windows Memory Diagnostic",
            "Update disk drivers",
            "Run disk check (chkdsk /f)",
            "Disable antivirus temporarily",
        ],
    },
    0x7A: {
        "name": "KERNEL_DATA_INPAGE_ERROR",
        "description": "The requested page of kernel data could not be read from disk.",
        "common_causes": [
            "Bad sectors on hard drive",
            "Faulty SATA controller",
            "Disk drive failure",
            "Virus infection",
        ],
        "recommendations": [
            "Run disk check (chkdsk /r)",
            "Check drive health with S.M.A.R.T. tools",
            "Backup important data immediately",
            "Consider replacing the drive",
        ],
    },
    0x7F: {
        "name": "UNEXPECTED_KERNEL_MODE_TRAP",
        "description": "A trap was generated by the kernel that the debugger couldn't catch.",
        "common_causes": [
            "Overheating CPU",
            "Overclocking instability",
            "Faulty hardware",
            "Memory issues",
        ],
        "recommendations": [
            "Check CPU temperature",
            "Disable overclocking",
            "Run memory diagnostic",
            "Update BIOS/UEFI",
        ],
    },
    0x1E: {
        "name": "KMODE_EXCEPTION_NOT_HANDLED",
        "description": "The kernel detected an exception it was not expecting.",
        "common_causes": [
            "Faulty driver",
            "Memory corruption",
            "Incompatible software",
        ],
        "recommendations": [
            "Update all drivers",
            "Uninstall recently installed software",
            "Run memory diagnostic",
            "Check Event Viewer for errors",
        ],
    },
    0x124: {
        "name": "WHEA_UNCORRECTABLE_ERROR",
        "description": "A fatal hardware error was reported by Windows Hardware Error Architecture.",
        "common_causes": [
            "CPU hardware failure",
            "Overheating",
            "Power supply issues",
            "Motherboard problems",
        ],
        "recommendations": [
            "Check CPU temperature",
            "Test with different power supply",
            "Update BIOS",
            "Contact hardware manufacturer for service",
        ],
    },
    0x133: {
        "name": "DPC_WATCHDOG_VIOLATION",
        "description": "The DPC watchdog detected a prolonged run time at an IRQL of DISPATCH_LEVEL or above.",
        "common_causes": [
            "Driver stuck in infinite loop",
            "SSD firmware issues",
            "Outdated drivers",
        ],
        "recommendations": [
            "Update SSD firmware",
            "Update all drivers",
            "Run System File Checker",
            "Perform a clean boot",
        ],
    },
    0xEF: {
        "name": "CRITICAL_PROCESS_DIED",
        "description": "A critical system process died.",
        "common_causes": [
            "System file corruption",
            "Disk corruption",
            "Malware infection",
            "Failed Windows update",
        ],
        "recommendations": [
            "Run System File Checker (sfc /scannow)",
            "Run DISM repair",
            "Check disk for errors",
            "Perform a system restore",
        ],
    },
    0x7E: {
        "name": "SYSTEM_THREAD_EXCEPTION_NOT_HANDLED",
        "description": "A system thread generated an exception which the error handler did not catch.",
        "common_causes": [
            "Video driver issues",
            "Faulty RAM",
            "Corrupted system files",
        ],
        "recommendations": [
            "Update video drivers",
            "Run memory diagnostic",
            "Run System File Checker",
            "Check for recent driver changes",
        ],
    },
    0x19: {
        "name": "BAD_POOL_HEADER",
        "description": "Memory pool header is corrupt.",
        "common_causes": [
            "Driver memory corruption",
            "Malware",
            "Faulty RAM",
        ],
        "recommendations": [
            "Update all drivers",
            "Run full system antivirus scan",
            "Run memory diagnostic",
            "Check for recently installed software",
        ],
    },
    0x1A: {
        "name": "MEMORY_MANAGEMENT",
        "description": "A severe memory management error occurred.",
        "common_causes": [
            "Faulty RAM",
            "Disk corruption",
            "Driver issues",
        ],
        "recommendations": [
            "Run Windows Memory Diagnostic",
            "Run disk check (chkdsk)",
            "Update drivers",
            "Increase virtual memory",
        ],
    },
    0xC4: {
        "name": "DRIVER_VERIFIER_DETECTED_VIOLATION",
        "description": "Driver Verifier detected a violation.",
        "common_causes": [
            "Driver is violating rules",
            "Specifically the driver being tested",
        ],
        "recommendations": [
            "Disable Driver Verifier if needed",
            "Update the problematic driver",
            "Check crash dump for specific driver name",
            "Uninstall the offending driver",
        ],
    },
    0xFC: {
        "name": "ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY",
        "description": "An attempt was made to execute non-executable memory.",
        "common_causes": [
            "Driver trying to execute NX-protected memory",
            "Malware infection",
            "Corrupted driver",
        ],
        "recommendations": [
            "Update all drivers",
            "Run full antivirus scan",
            "Check for recently installed drivers",
            "Enable DEP and check compatibility",
        ],
    },
    0x2D: {
        "name": "HARDWARE_PROFILE_DISK_SIZE_ERROR",
        "description": "A hardware profile disk size error occurred. This can indicate issues with the system's hardware profile storage or disk configuration.",
        "common_causes": [
            "Corrupted hardware profile registry data",
            "Disk space or configuration issues",
            "System hive corruption",
            "Storage driver problems",
        ],
        "recommendations": [
            "Check disk space and disk health",
            "Run System File Checker (sfc /scannow)",
            "Check for storage driver updates",
            "Review Event Viewer for disk-related errors",
        ],
    },
}


class BugcheckKnowledgeBase:
    """Knowledge base for bugcheck codes."""

    def __init__(self):
        """Initialize the knowledge base."""
        self._data = BUGCHECK_CODES

    def get_bugcheck_info(self, code: int) -> tuple[str, str]:
        """Get bugcheck name and description for a code."""
        if code in self._data:
            info = self._data[code]
            return info["name"], info["description"]
        return f"UNKNOWN_0x{code:02X}", f"Unknown bugcheck code: 0x{code:02X}"

    def get_description(self, code: int) -> str:
        """Get description for a bugcheck code."""
        if code in self._data:
            return self._data[code]["description"]
        return f"Unknown bugcheck code: 0x{code:02X}"

    def get_common_causes(self, code: int) -> List[str]:
        """Get common causes for a bugcheck code."""
        if code in self._data:
            return self._data[code]["common_causes"]
        return ["Unknown cause"]

    def get_recommendations(self, code: int) -> List[str]:
        """Get recommendations for a bugcheck code."""
        if code in self._data:
            return self._data[code]["recommendations"]
        return [
            "Check Event Viewer for detailed error information",
            "Update Windows and all drivers",
            "Run System File Checker (sfc /scannow)",
        ]

    def get_all_codes(self) -> dict:
        """Get all bugcheck codes."""
        return self._data
